# Generated by Django 4.0 on 2022-02-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_rename_user_blogpost_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='user1',
            new_name='user',
        ),
    ]
